import { Metadata } from "next";
import Link from "next/link";
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { CheckCircle, PenTool, FileText, BookOpen, Search, Globe, Edit, Users, Clock, Shield, Award } from "lucide-react";
export const metadata: Metadata = { title: "Article Writing Services | CogniCode", description: "Professional academic article writing for peer-reviewed journals, magazines, and academic platforms." };
const features = [
  { icon: PenTool, title: "Journal Article Writing", description: "Original research articles crafted to meet the rigorous standards of peer-reviewed academic journals." },
  { icon: BookOpen, title: "Review Articles", description: "Comprehensive review articles that survey, critique, and synthesize existing research on a specific topic." },
  { icon: Search, title: "Abstract & Keywords", description: "SEO-optimized abstracts and keyword selection to maximize discoverability and indexing." },
  { icon: FileText, title: "Proper Formatting", description: "Expert formatting in APA, MLA, Chicago, Harvard, IEEE, and other citation styles as per journal requirements." },
  { icon: Globe, title: "Journal Targeting", description: "Strategic journal selection based on scope, impact factor, acceptance rates, and alignment with your research." },
  { icon: Edit, title: "Revision Support", description: "Comprehensive revision support including response to reviewer comments and resubmission assistance." },
];
const steps = [
  { step: "01", title: "Topic & Scope Discussion", description: "Understand the subject, target journal, and specific requirements for the article." },
  { step: "02", title: "Research & Outlining", description: "Conduct thorough research and create a detailed outline for your approval." },
  { step: "03", title: "Writing & Formatting", description: "Write the article with proper structure, citations, and journal-specific formatting." },
  { step: "04", title: "Review & Submission", description: "Multiple revision rounds followed by submission-ready final delivery." },
];
const benefits = ["Subject-matter expert writers", "Publication-ready quality output", "Multiple journal format expertise", "Fast turnaround options available", "Unlimited revisions included", "Confidentiality guaranteed", "Plagiarism-free with Turnitin report", "Reviewer response support included"];
export default function ArticleWritingPage() {
  return (<div className="flex min-h-screen flex-col"><Header /><main className="flex-1 mt-17">
    <section className="bg-primary/5 py-16 md:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-12 lg:grid-cols-2 lg:items-center"><div><p className="text-sm font-semibold uppercase tracking-wider text-primary">Article Writing</p><h1 className="mt-2 font-serif text-4xl font-bold tracking-tight text-foreground sm:text-5xl">Professional Article Writing Services</h1><p className="mt-6 text-lg leading-8 text-muted-foreground">High-quality academic articles crafted by subject-matter experts for peer-reviewed journals, industry magazines, and academic platforms worldwide.</p><div className="mt-8 flex flex-col gap-4 sm:flex-row"><Button size="lg" asChild><Link href="/contact">Get Article Support</Link></Button><Button size="lg" variant="outline" asChild><Link href="/samples">View Samples</Link></Button></div></div><div className="space-y-4"><Card className="bg-primary text-primary-foreground"><CardContent className="p-6"><div className="flex items-center gap-4"><PenTool className="h-12 w-12" /><div><p className="text-3xl font-bold">5000+</p><p className="text-sm text-primary-foreground/80">Articles Published</p></div></div></CardContent></Card><div className="grid grid-cols-2 gap-4"><Card><CardContent className="p-6 text-center"><p className="text-2xl font-bold text-primary">85%</p><p className="text-sm text-muted-foreground">Acceptance Rate</p></CardContent></Card><Card><CardContent className="p-6 text-center"><p className="text-2xl font-bold text-primary">300+</p><p className="text-sm text-muted-foreground">Journals Covered</p></CardContent></Card></div></div></div></div></section>
    <section className="bg-primary py-8"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="flex flex-wrap items-center justify-center gap-8">{[{ icon: Shield, text: "100% Original" }, { icon: Clock, text: "On-Time Delivery" }, { icon: Users, text: "Expert Writers" }, { icon: Award, text: "Publication Ready" }].map((item, i) => (<div key={i} className="flex items-center gap-2 text-primary-foreground"><item.icon className="h-5 w-5" /><span className="text-sm font-medium">{item.text}</span></div>))}</div></div></section>
    <section className="py-16 md:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mx-auto max-w-2xl text-center"><h2 className="font-serif text-3xl font-bold tracking-tight text-foreground sm:text-4xl">Our Article Writing Expertise</h2><p className="mt-4 text-lg text-muted-foreground">Comprehensive article writing support from concept to publication.</p></div><div className="mt-16 grid gap-8 md:grid-cols-2 lg:grid-cols-3">{features.map((f, i) => (<Card key={i} className="border-none shadow-lg hover:shadow-xl transition-shadow"><CardContent className="p-6"><div className="flex h-12 w-12 items-center justify-center rounded-lg bg-primary/10"><f.icon className="h-6 w-6 text-primary" /></div><h3 className="mt-4 text-lg font-semibold text-foreground">{f.title}</h3><p className="mt-2 text-muted-foreground">{f.description}</p></CardContent></Card>))}</div></div></section>
    <section className="bg-muted/50 py-16 md:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mx-auto max-w-2xl text-center mb-16"><h2 className="font-serif text-3xl font-bold tracking-tight text-foreground sm:text-4xl">Our Writing Process</h2><p className="mt-4 text-lg text-muted-foreground">A proven 4-step approach to delivering publication-quality articles.</p></div><div className="grid gap-8 md:grid-cols-2 lg:grid-cols-4">{steps.map((s, i) => (<div key={i} className="text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-primary text-2xl font-bold text-primary-foreground">{s.step}</div><h3 className="mt-4 font-semibold text-foreground">{s.title}</h3><p className="mt-2 text-sm text-muted-foreground">{s.description}</p></div>))}</div></div></section>
    <section className="py-16 md:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-12 lg:grid-cols-2 lg:items-center"><div><h2 className="font-serif text-3xl font-bold tracking-tight text-foreground sm:text-4xl">Why Choose Our Article Writing?</h2><p className="mt-4 text-lg text-muted-foreground">Expert writers who understand what journals look for.</p><ul className="mt-8 grid gap-3 sm:grid-cols-2">{benefits.map((b, i) => (<li key={i} className="flex items-start gap-2"><CheckCircle className="mt-0.5 h-5 w-5 shrink-0 text-primary" /><span className="text-sm text-muted-foreground">{b}</span></li>))}</ul></div><Card><CardContent className="p-8"><h3 className="text-xl font-semibold text-foreground">Get a Free Quote</h3><p className="mt-2 text-muted-foreground">Share your article requirements and get expert guidance.</p><form className="mt-6 space-y-4"><input type="text" placeholder="Your Name" className="w-full rounded-lg border border-border bg-background px-4 py-3 text-sm focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary" /><input type="email" placeholder="Email Address" className="w-full rounded-lg border border-border bg-background px-4 py-3 text-sm focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary" /><input type="tel" placeholder="Phone Number" className="w-full rounded-lg border border-border bg-background px-4 py-3 text-sm focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary" /><select className="w-full rounded-lg border border-border bg-background px-4 py-3 text-sm text-muted-foreground focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"><option value="">Select Article Type</option><option value="research">Research Article</option><option value="review">Review Article</option><option value="case">Case Study</option><option value="technical">Technical Article</option></select><Button className="w-full" size="lg">Get Free Quote</Button></form></CardContent></Card></div></div></section>
    <section className="bg-primary py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 text-center"><h2 className="font-serif text-3xl font-bold text-primary-foreground sm:text-4xl">Ready to Publish Your Research?</h2><p className="mx-auto mt-4 max-w-2xl text-lg text-primary-foreground/90">Let our expert writers help you publish in top-tier journals.</p><div className="mt-8 flex flex-col items-center justify-center gap-4 sm:flex-row"><Button size="lg" variant="secondary" asChild><Link href="/contact">Get Started</Link></Button><Button size="lg" variant="outline" className="border-primary-foreground text-black hover:bg-primary-foreground hover:text-primary" asChild><Link href="/pricing">View Pricing</Link></Button></div></div></section>
  </main><Footer /></div>);
}
