import { Metadata } from "next";
import Link from "next/link";
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { CheckCircle, FileText, BookOpen, Search, Globe, Edit, BarChart3, Users, Clock, Shield, Award, PenTool,Bookmark,Image,Printer } from "lucide-react";
export const metadata: Metadata = { title: "Book Writing & Publishing | CogniCode", description: "End-to-end academic book writing and publishing support. From concept to bookshelf." };
const features = [
  { icon: PenTool, title: "Book Proposal & Outline", description: "Develop a compelling book proposal and detailed chapter outline that publishers find irresistible." },
  { icon: BookOpen, title: "Chapter Writing", description: "Expert chapter-by-chapter writing support ensuring consistency, depth, and academic rigor." },
  { icon: Globe, title: "Publisher Outreach", description: "Identification of suitable academic publishers, preparation of pitch materials, and negotiation support." },
  { icon: Bookmark, title: "ISBN & Copyright", description: "Assistance with ISBN registration, copyright filing, and all legal formalities for your publication." },
  { icon: Image, title: "Cover Design & Typesetting", description: "Professional book cover design, interior layout, typesetting, and formatting for print and digital." },
  { icon: Printer, title: "Print & E-Book Setup", description: "Complete setup for print-on-demand (Amazon KDP, IngramSpark) and e-book distribution channels." },
];
const steps = [
  { step: "01", title: "Concept Development", description: "Define the book scope, target audience, unique value proposition, and chapter structure." },
  { step: "02", title: "Writing & Editing", description: "Write, edit, and polish the manuscript chapter by chapter with progress reviews." },
  { step: "03", title: "Publisher Outreach", description: "Identify suitable publishers, prepare compelling proposals, and manage submission." },
  { step: "04", title: "Publication & Launch", description: "Manage the production process from typesetting to final publication and distribution." },
];
const benefits = ["End-to-end publishing support", "Connections with academic publishers", "ISBN and indexing assistance", "Professional typesetting and design", "Marketing and distribution guidance", "Royalty and contract advice", "Both print and digital publishing", "Post-publication promotion support"];
export default function ServicePage() {
  return (<div className="flex min-h-screen flex-col"><Header /><main className="flex-1 mt-17">
    <section className="bg-primary/5 py-16 md:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-12 lg:grid-cols-2 lg:items-center"><div><p className="text-sm font-semibold uppercase tracking-wider text-primary">Book Writing & Publishing</p><h1 className="mt-2 font-serif text-4xl font-bold tracking-tight text-foreground sm:text-5xl">Academic Book Writing & Publishing Services</h1><p className="mt-6 text-lg leading-8 text-muted-foreground">Transform your expertise into a published book. From concept development and manuscript writing to publisher negotiations and distribution : we handle every step of your publishing journey.</p><div className="mt-8 flex flex-col gap-4 sm:flex-row"><Button size="lg" asChild><Link prefetch={false} href="/contact">Get Started</Link></Button><Button size="lg" variant="outline" asChild><Link prefetch={false} href="/samples">View Samples</Link></Button></div></div><div className="space-y-4"><Card className="bg-primary text-primary-foreground"><CardContent className="p-6"><div className="flex items-center gap-4"><BookOpen className="h-12 w-12" /><div><p className="text-3xl font-bold">500+</p><p className="text-sm text-primary-foreground/80">Books Published</p></div></div></CardContent></Card><div className="grid grid-cols-2 gap-4"><Card><CardContent className="p-6 text-center"><p className="text-2xl font-bold text-primary">50+</p><p className="text-sm text-muted-foreground">Publishers Network</p></CardContent></Card><Card><CardContent className="p-6 text-center"><p className="text-2xl font-bold text-primary">100%</p><p className="text-sm text-muted-foreground">ISBN Assistance</p></CardContent></Card></div></div></div></div></section>
    <section className="bg-primary py-8"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="flex flex-wrap items-center justify-center gap-8">{[{ icon: Shield, text: "100% Original" }, { icon: Clock, text: "On-Time Delivery" }, { icon: Users, text: "Expert Writers" }, { icon: Award, text: "Quality Assured" }].map((item, i) => (<div key={i} className="flex items-center gap-2 text-primary-foreground"><item.icon className="h-5 w-5" /><span className="text-sm font-medium">{item.text}</span></div>))}</div></div></section>
    <section className="py-16 md:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mx-auto max-w-2xl text-center"><h2 className="font-serif text-3xl font-bold tracking-tight text-foreground sm:text-4xl">Our Publishing Services</h2><p className="mt-4 text-lg text-muted-foreground">Comprehensive support for every aspect of your project.</p></div><div className="mt-16 grid gap-8 md:grid-cols-2 lg:grid-cols-3">{features.map((f, i) => (<Card key={i} className="border-none shadow-lg hover:shadow-xl transition-shadow"><CardContent className="p-6"><div className="flex h-12 w-12 items-center justify-center rounded-lg bg-primary/10"><f.icon className="h-6 w-6 text-primary" /></div><h3 className="mt-4 text-lg font-semibold text-foreground">{f.title}</h3><p className="mt-2 text-muted-foreground">{f.description}</p></CardContent></Card>))}</div></div></section>
    <section className="bg-muted/50 py-16 md:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mx-auto max-w-2xl text-center mb-16"><h2 className="font-serif text-3xl font-bold tracking-tight text-foreground sm:text-4xl">Our Process</h2><p className="mt-4 text-lg text-muted-foreground">A structured approach to ensure your success.</p></div><div className="grid gap-8 md:grid-cols-2 lg:grid-cols-4">{steps.map((s, i) => (<div key={i} className="text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-primary text-2xl font-bold text-primary-foreground">{s.step}</div><h3 className="mt-4 font-semibold text-foreground">{s.title}</h3><p className="mt-2 text-sm text-muted-foreground">{s.description}</p></div>))}</div></div></section>
    <section className="py-16 md:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-12 lg:grid-cols-2 lg:items-center"><div><h2 className="font-serif text-3xl font-bold tracking-tight text-foreground sm:text-4xl">Why Publish With Us?</h2><p className="mt-4 text-lg text-muted-foreground">Here is why scholars trust us with their work.</p><ul className="mt-8 grid gap-3 sm:grid-cols-2">{benefits.map((b, i) => (<li key={i} className="flex items-start gap-2"><CheckCircle className="mt-0.5 h-5 w-5 shrink-0 text-primary" /><span className="text-sm text-muted-foreground">{b}</span></li>))}</ul></div><Card><CardContent className="p-8"><h3 className="text-xl font-semibold text-foreground">Get a Free Consultation</h3><p className="mt-2 text-muted-foreground">Share your requirements and get expert guidance.</p><form className="mt-6 space-y-4"><input type="text" placeholder="Your Name" className="w-full rounded-lg border border-border bg-background px-4 py-3 text-sm focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary" /><input type="email" placeholder="Email Address" className="w-full rounded-lg border border-border bg-background px-4 py-3 text-sm focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary" /><input type="tel" placeholder="Phone Number" className="w-full rounded-lg border border-border bg-background px-4 py-3 text-sm focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary" /><select className="w-full rounded-lg border border-border bg-background px-4 py-3 text-sm text-muted-foreground focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"><option value="">Select Book Type</option><option value="textbook">Academic Textbook</option><option value="monograph">Research Monograph</option><option value="edited">Edited Volume</option><option value="professional">Professional Guide</option><option value="other">Other</option></select><Button className="w-full" size="lg">Get Free Consultation</Button></form></CardContent></Card></div></div></section>
    <section className="bg-primary py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 text-center"><h2 className="font-serif text-3xl font-bold text-primary-foreground sm:text-4xl">Ready to Become a Published Author?</h2><p className="mx-auto mt-4 max-w-2xl text-lg text-primary-foreground/90">Your knowledge deserves to reach a wider audience. Let us make it happen.</p><div className="mt-8 flex flex-col items-center justify-center gap-4 sm:flex-row"><Button size="lg" variant="secondary" asChild><Link prefetch={false} href="/contact">Get Started</Link></Button><Button size="lg" variant="outline" className="border-primary-foreground text-black hover:bg-primary-foreground hover:text-primary" asChild><Link prefetch={false} href="/pricing">View Pricing</Link></Button></div></div></section>
  </main><Footer /></div>);
}
