import { Metadata } from "next";
import Link from "next/link";
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { CheckCircle, FileText, Search, BarChart3, Users, Clock, Shield, Award, TrendingUp,Table, Layers } from "lucide-react";
import { Layer } from "recharts";
export const metadata: Metadata = { title: "Review Paper Writing | CogniCodeWrite", description: "Expert review paper writing that surveys, critiques, and synthesizes existing research for high-impact journals." };
const features = [
  { icon: Search, title: "Comprehensive Survey", description: "Exhaustive survey of your research domain covering hundreds of papers with documented methodology." },
  { icon: Layer, title: "Systematic Approach", description: "Choice of systematic, scoping, narrative, or meta-analytic review methodologies for your goals." },
  { icon: BarChart3, title: "Comparative Analysis", description: "Detailed comparison of methodologies, algorithms, frameworks, and findings across studies." },
  { icon: TrendingUp, title: "Trend Identification", description: "Identification of emerging trends, paradigm shifts, and future research directions." },
  { icon: Table, title: "Taxonomy & Classification", description: "Creation of classification frameworks, comparison tables, and taxonomies for the landscape." },
  { icon: FileText, title: "Journal-Ready Format", description: "Manuscript prepared in the exact format of your target journal with all required sections." },
];
const steps = [
  { step: "01", title: "Domain Scoping", description: "Define the scope, objectives, and type of review — systematic, scoping, or narrative." },
  { step: "02", title: "Paper Collection", description: "Collect and screen hundreds of papers using inclusion and exclusion criteria." },
  { step: "03", title: "Critical Analysis", description: "Analyze, compare, and synthesize papers into meaningful categories and insights." },
  { step: "04", title: "Manuscript Writing", description: "Write the review paper with proper structure, tables, and journal formatting." },
];
const benefits = ["High citation potential papers", "Experienced review paper writers", "Suitable for Q1/Q2 journal submission", "Comprehensive and authoritative coverage", "Publication support included", "Fully original and plagiarism-free", "Meta-analysis support where applicable", "Visual summaries and comparison tables"];
export default function ServicePage() {
  return (<div className="flex min-h-screen flex-col"><Header /><main className="flex-1 mt-17">
    <section className="bg-primary/5 py-16 md:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-12 lg:grid-cols-2 lg:items-center"><div><p className="text-sm font-semibold uppercase tracking-wider text-primary">Review Paper Writing</p><h1 className="mt-2 font-serif text-4xl font-bold tracking-tight text-foreground sm:text-5xl">Expert Review Paper Writing Services</h1><p className="mt-6 text-lg leading-8 text-muted-foreground">Produce authoritative survey and review articles that comprehensively cover your research domain, identify trends, compare methodologies, and provide future research directions for high-impact journal publication.</p><div className="mt-8 flex flex-col gap-4 sm:flex-row"><Button size="lg" asChild><Link href="/contact">Get Started</Link></Button><Button size="lg" variant="outline" asChild><Link href="/samples">View Samples</Link></Button></div></div><div className="space-y-4"><Card className="bg-primary text-primary-foreground"><CardContent className="p-6"><div className="flex items-center gap-4"><Layers className="h-12 w-12" /><div><p className="text-3xl font-bold">1500+</p><p className="text-sm text-primary-foreground/80">Review Papers Published</p></div></div></CardContent></Card><div className="grid grid-cols-2 gap-4"><Card><CardContent className="p-6 text-center"><p className="text-2xl font-bold text-primary">300+</p><p className="text-sm text-muted-foreground">Papers per Review</p></CardContent></Card><Card><CardContent className="p-6 text-center"><p className="text-2xl font-bold text-primary">High</p><p className="text-sm text-muted-foreground">Citation Potential</p></CardContent></Card></div></div></div></div></section>
    <section className="bg-primary py-8"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="flex flex-wrap items-center justify-center gap-8">{[{ icon: Shield, text: "100% Original" }, { icon: Clock, text: "On-Time Delivery" }, { icon: Users, text: "Expert Writers" }, { icon: Award, text: "Quality Assured" }].map((item, i) => (<div key={i} className="flex items-center gap-2 text-primary-foreground"><item.icon className="h-5 w-5" /><span className="text-sm font-medium">{item.text}</span></div>))}</div></div></section>
    <section className="py-16 md:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mx-auto max-w-2xl text-center"><h2 className="font-serif text-3xl font-bold tracking-tight text-foreground sm:text-4xl">What Makes Our Review Papers Stand Out</h2><p className="mt-4 text-lg text-muted-foreground">Comprehensive support for every aspect of your project.</p></div><div className="mt-16 grid gap-8 md:grid-cols-2 lg:grid-cols-3">{features.map((f, i) => (<Card key={i} className="border-none shadow-lg hover:shadow-xl transition-shadow"><CardContent className="p-6"><div className="flex h-12 w-12 items-center justify-center rounded-lg bg-primary/10"><f.icon className="h-6 w-6 text-primary" /></div><h3 className="mt-4 text-lg font-semibold text-foreground">{f.title}</h3><p className="mt-2 text-muted-foreground">{f.description}</p></CardContent></Card>))}</div></div></section>
    <section className="bg-muted/50 py-16 md:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mx-auto max-w-2xl text-center mb-16"><h2 className="font-serif text-3xl font-bold tracking-tight text-foreground sm:text-4xl">Our Process</h2><p className="mt-4 text-lg text-muted-foreground">A structured approach to ensure your success.</p></div><div className="grid gap-8 md:grid-cols-2 lg:grid-cols-4">{steps.map((s, i) => (<div key={i} className="text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-primary text-2xl font-bold text-primary-foreground">{s.step}</div><h3 className="mt-4 font-semibold text-foreground">{s.title}</h3><p className="mt-2 text-sm text-muted-foreground">{s.description}</p></div>))}</div></div></section>
    <section className="py-16 md:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-12 lg:grid-cols-2 lg:items-center"><div><h2 className="font-serif text-3xl font-bold tracking-tight text-foreground sm:text-4xl">Why Choose Us for Review Papers?</h2><p className="mt-4 text-lg text-muted-foreground">Here is why scholars trust us with their work.</p><ul className="mt-8 grid gap-3 sm:grid-cols-2">{benefits.map((b, i) => (<li key={i} className="flex items-start gap-2"><CheckCircle className="mt-0.5 h-5 w-5 shrink-0 text-primary" /><span className="text-sm text-muted-foreground">{b}</span></li>))}</ul></div><Card><CardContent className="p-8"><h3 className="text-xl font-semibold text-foreground">Get a Free Consultation</h3><p className="mt-2 text-muted-foreground">Share your requirements and get expert guidance.</p><form className="mt-6 space-y-4"><input type="text" placeholder="Your Name" className="w-full rounded-lg border border-border bg-background px-4 py-3 text-sm focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary" /><input type="email" placeholder="Email Address" className="w-full rounded-lg border border-border bg-background px-4 py-3 text-sm focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary" /><input type="tel" placeholder="Phone Number" className="w-full rounded-lg border border-border bg-background px-4 py-3 text-sm focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary" /><select className="w-full rounded-lg border border-border bg-background px-4 py-3 text-sm text-muted-foreground focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"><option value="">Select Review Type</option><option value="systematic">Systematic Review</option><option value="survey">Survey Paper</option><option value="meta">Meta-Analysis</option><option value="narrative">Narrative Review</option></select><Button className="w-full" size="lg">Get Free Consultation</Button></form></CardContent></Card></div></div></section>
    <section className="bg-primary py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 text-center"><h2 className="font-serif text-3xl font-bold text-primary-foreground sm:text-4xl">Publish a High-Impact Review Paper</h2><p className="mx-auto mt-4 max-w-2xl text-lg text-primary-foreground/90">Review papers attract the most citations. Let us help you write one.</p><div className="mt-8 flex flex-col items-center justify-center gap-4 sm:flex-row"><Button size="lg" variant="secondary" asChild><Link href="/contact">Get Started</Link></Button><Button size="lg" variant="outline" className="border-primary-foreground text-primary-foreground hover:bg-primary-foreground hover:text-primary" asChild><Link href="/pricing">View Pricing</Link></Button></div></div></section>
  </main><Footer /></div>);
}
