import { Metadata } from "next";
import Link from "next/link";
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { CheckCircle, FileText, Globe, BarChart3, Users, Clock, Shield, Award, Search,Star, TrendingUp } from "lucide-react";
export const metadata: Metadata = { title: "Scopus Paper Writing | CogniCode", description: "Expert Scopus-indexed journal paper writing. Boost your academic profile, h-index, and citation count." };
const features = [
  { icon: Search, title: "Journal Selection", description: "Strategic identification of Scopus-indexed journals that best match your research area and goals." },
  { icon: TrendingUp, title: "Impact Factor Analysis", description: "Evaluation of journal impact factors, quartile rankings, and acceptance rates to target the right venue." },
  { icon: FileText, title: "Manuscript Preparation", description: "Complete manuscript writing following the target journal author guidelines and formatting." },
  { icon: BarChart3, title: "Data & Results", description: "Professional statistical analysis and results presentation meeting Scopus quality benchmarks." },
  { icon: Globe, title: "Indexing Optimization", description: "Abstract and keyword optimization for maximum discoverability in Scopus and Google Scholar." },
  { icon: Star, title: "Peer Review Support", description: "Assistance with responding to reviewer comments, manuscript revisions, and resubmission." },
];
const steps = [
  { step: "01", title: "Research & Journal Mapping", description: "Identify the best Scopus-indexed journals aligned with your research area and goals." },
  { step: "02", title: "Manuscript Writing", description: "Write the full manuscript following the target journal author guidelines." },
  { step: "03", title: "Internal Peer Review", description: "Our internal reviewers evaluate the paper against Scopus quality standards." },
  { step: "04", title: "Submission & Follow-Up", description: "Assist with journal submission portal and respond to reviewer comments." },
];
const benefits = ["Proven Scopus publication track record", "Journal selection with impact factor analysis", "Reviewer response and revision support", "Original and plagiarism-free work guaranteed", "Boost your h-index and citation count", "Confidential and timely delivery", "Q1 and Q2 journal targeting available", "Subject-specific expert writers"];
export default function ServicePage() {
  return (<div className="flex min-h-screen flex-col"><Header /><main className="flex-1 mt-17">
    <section className="bg-primary/5 py-16 md:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-12 lg:grid-cols-2 lg:items-center"><div><p className="text-sm font-semibold uppercase tracking-wider text-primary">Scopus Paper Writing</p><h1 className="mt-2 font-serif text-4xl font-bold tracking-tight text-foreground sm:text-5xl">Scopus-Indexed Paper Writing Services</h1><p className="mt-6 text-lg leading-8 text-muted-foreground">Publish in Scopus-indexed journals with confidence. We specialize in crafting high-quality manuscripts that meet rigorous indexing standards and help you build a strong academic profile.</p><div className="mt-8 flex flex-col gap-4 sm:flex-row"><Button size="lg" asChild><Link href="/contact">Get Started</Link></Button><Button size="lg" variant="outline" asChild><Link href="/samples">View Samples</Link></Button></div></div><div className="space-y-4"><Card className="bg-primary text-primary-foreground"><CardContent className="p-6"><div className="flex items-center gap-4"><TrendingUp className="h-12 w-12" /><div><p className="text-3xl font-bold">2500+</p><p className="text-sm text-primary-foreground/80">Scopus Papers Published</p></div></div></CardContent></Card><div className="grid grid-cols-2 gap-4"><Card><CardContent className="p-6 text-center"><p className="text-2xl font-bold text-primary">88%</p><p className="text-sm text-muted-foreground">Acceptance Rate</p></CardContent></Card><Card><CardContent className="p-6 text-center"><p className="text-2xl font-bold text-primary">500+</p><p className="text-sm text-muted-foreground">Scopus Journals</p></CardContent></Card></div></div></div></div></section>
    <section className="bg-primary py-8"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="flex flex-wrap items-center justify-center gap-8">{[{ icon: Shield, text: "100% Original" }, { icon: Clock, text: "On-Time Delivery" }, { icon: Users, text: "Expert Writers" }, { icon: Award, text: "Quality Assured" }].map((item, i) => (<div key={i} className="flex items-center gap-2 text-primary-foreground"><item.icon className="h-5 w-5" /><span className="text-sm font-medium">{item.text}</span></div>))}</div></div></section>
    <section className="py-16 md:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mx-auto max-w-2xl text-center"><h2 className="font-serif text-3xl font-bold tracking-tight text-foreground sm:text-4xl">Our Scopus Paper Expertise</h2><p className="mt-4 text-lg text-muted-foreground">Comprehensive support for every aspect of your project.</p></div><div className="mt-16 grid gap-8 md:grid-cols-2 lg:grid-cols-3">{features.map((f, i) => (<Card key={i} className="border-none shadow-lg hover:shadow-xl transition-shadow"><CardContent className="p-6"><div className="flex h-12 w-12 items-center justify-center rounded-lg bg-primary/10"><f.icon className="h-6 w-6 text-primary" /></div><h3 className="mt-4 text-lg font-semibold text-foreground">{f.title}</h3><p className="mt-2 text-muted-foreground">{f.description}</p></CardContent></Card>))}</div></div></section>
    <section className="bg-muted/50 py-16 md:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mx-auto max-w-2xl text-center mb-16"><h2 className="font-serif text-3xl font-bold tracking-tight text-foreground sm:text-4xl">Our Process</h2><p className="mt-4 text-lg text-muted-foreground">A structured approach to ensure your success.</p></div><div className="grid gap-8 md:grid-cols-2 lg:grid-cols-4">{steps.map((s, i) => (<div key={i} className="text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-primary text-2xl font-bold text-primary-foreground">{s.step}</div><h3 className="mt-4 font-semibold text-foreground">{s.title}</h3><p className="mt-2 text-sm text-muted-foreground">{s.description}</p></div>))}</div></div></section>
    <section className="py-16 md:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-12 lg:grid-cols-2 lg:items-center"><div><h2 className="font-serif text-3xl font-bold tracking-tight text-foreground sm:text-4xl">Why Choose Us for Scopus Papers?</h2><p className="mt-4 text-lg text-muted-foreground">Here is why scholars trust us with their work.</p><ul className="mt-8 grid gap-3 sm:grid-cols-2">{benefits.map((b, i) => (<li key={i} className="flex items-start gap-2"><CheckCircle className="mt-0.5 h-5 w-5 shrink-0 text-primary" /><span className="text-sm text-muted-foreground">{b}</span></li>))}</ul></div><Card><CardContent className="p-8"><h3 className="text-xl font-semibold text-foreground">Get a Free Consultation</h3><p className="mt-2 text-muted-foreground">Share your requirements and get expert guidance.</p><form className="mt-6 space-y-4"><input type="text" placeholder="Your Name" className="w-full rounded-lg border border-border bg-background px-4 py-3 text-sm focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary" /><input type="email" placeholder="Email Address" className="w-full rounded-lg border border-border bg-background px-4 py-3 text-sm focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary" /><input type="tel" placeholder="Phone Number" className="w-full rounded-lg border border-border bg-background px-4 py-3 text-sm focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary" /><select className="w-full rounded-lg border border-border bg-background px-4 py-3 text-sm text-muted-foreground focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"><option value="">Select Subject Area</option><option value="engineering">Engineering</option><option value="management">Management</option><option value="sciences">Sciences</option><option value="medical">Medical Sciences</option><option value="social">Social Sciences</option><option value="other">Other</option></select><Button className="w-full" size="lg">Get Free Consultation</Button></form></CardContent></Card></div></div></section>
    <section className="bg-primary py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 text-center"><h2 className="font-serif text-3xl font-bold text-primary-foreground sm:text-4xl">Ready to Publish in Scopus?</h2><p className="mx-auto mt-4 max-w-2xl text-lg text-primary-foreground/90">Boost your academic profile with a Scopus-indexed publication.</p><div className="mt-8 flex flex-col items-center justify-center gap-4 sm:flex-row"><Button size="lg" variant="secondary" asChild><Link href="/contact">Get Started</Link></Button><Button size="lg" variant="outline" className="border-primary-foreground text-black hover:bg-primary-foreground hover:text-primary" asChild><Link href="/pricing">View Pricing</Link></Button></div></div></section>
  </main><Footer /></div>);
}
