import { Metadata } from "next";
import Link from "next/link";
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { CheckCircle, FileText, BookOpen, Search, Globe, Edit, BarChart3, PenTool, Users, Clock, Shield, Award, Filter,Layers,GitBranch,Database } from "lucide-react";
export const metadata: Metadata = { title: "Literature Review Writing | CogniCode", description: "Comprehensive, well-structured literature reviews that establish your research foundation and identify gaps." };
const features = [
  { icon: Search, title: "Systematic Search", description: "Comprehensive search across Scopus, Web of Science, PubMed, Google Scholar, and other databases." },
  { icon: Filter, title: "Critical Analysis", description: "In-depth critical evaluation of each source assessing methodology, findings, and limitations." },
  { icon: Layers, title: "Thematic Synthesis", description: "Organizing literature into coherent themes, trends, and narratives that build a strong argument." },
  { icon: GitBranch, title: "Gap Identification", description: "Systematic identification of research gaps that position your study as a necessary contribution." },
  { icon: Database, title: "Source Management", description: "Proper citation management with Mendeley, Zotero, and EndNote in APA, Harvard, or MLA." },
  { icon: BookOpen, title: "Visual Mapping", description: "Concept maps, literature matrices, and visual frameworks to illustrate relationships between studies." },
];
const steps = [
  { step: "01", title: "Scope Definition", description: "Define research questions, keywords, databases, and inclusion/exclusion criteria." },
  { step: "02", title: "Literature Search", description: "Systematic search across multiple databases with documented search strategy." },
  { step: "03", title: "Analysis & Synthesis", description: "Critically evaluate and synthesize findings into coherent themes and narratives." },
  { step: "04", title: "Review Writing", description: "Write a well-structured review that presents gaps and positions your research." },
];
const benefits = ["Access to premium academic databases", "PhD-level analytical writing quality", "Proper APA/Harvard/MLA formatting", "Gap analysis for research positioning", "Visual concept maps available", "Revision support included", "PRISMA guidelines followed where applicable", "Comprehensive reference list delivery"];
export default function ServicePage() {
  return (<div className="flex min-h-screen flex-col"><Header /><main className="flex-1 mt-17">
    <section className="bg-primary/5 py-16 md:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-12 lg:grid-cols-2 lg:items-center"><div><p className="text-sm font-semibold uppercase tracking-wider text-primary">Literature Review Writing</p><h1 className="mt-2 font-serif text-4xl font-bold tracking-tight text-foreground sm:text-5xl">Expert Literature Review Writing Services</h1><p className="mt-6 text-lg leading-8 text-muted-foreground">Build a rock-solid research foundation with our comprehensive literature review service. We systematically identify, evaluate, and synthesize relevant research to position your study within the broader academic conversation.</p><div className="mt-8 flex flex-col gap-4 sm:flex-row"><Button size="lg" asChild><Link prefetch={false} href="/contact">Get Started</Link></Button><Button size="lg" variant="outline" asChild><Link prefetch={false} href="/samples">View Samples</Link></Button></div></div><div className="space-y-4"><Card className="bg-primary text-primary-foreground"><CardContent className="p-6"><div className="flex items-center gap-4"><BookOpen className="h-12 w-12" /><div><p className="text-3xl font-bold">8000+</p><p className="text-sm text-primary-foreground/80">Literature Reviews Completed</p></div></div></CardContent></Card><div className="grid grid-cols-2 gap-4"><Card><CardContent className="p-6 text-center"><p className="text-2xl font-bold text-primary">200+</p><p className="text-sm text-muted-foreground">Sources per Review</p></CardContent></Card><Card><CardContent className="p-6 text-center"><p className="text-2xl font-bold text-primary">10 Days</p><p className="text-sm text-muted-foreground">Average Delivery</p></CardContent></Card></div></div></div></div></section>
    <section className="bg-primary py-8"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="flex flex-wrap items-center justify-center gap-8">{[{ icon: Shield, text: "100% Original" }, { icon: Clock, text: "On-Time Delivery" }, { icon: Users, text: "Expert Writers" }, { icon: Award, text: "Quality Assured" }].map((item, i) => (<div key={i} className="flex items-center gap-2 text-primary-foreground"><item.icon className="h-5 w-5" /><span className="text-sm font-medium">{item.text}</span></div>))}</div></div></section>
    <section className="py-16 md:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mx-auto max-w-2xl text-center"><h2 className="font-serif text-3xl font-bold tracking-tight text-foreground sm:text-4xl">Our Literature Review Approach</h2><p className="mt-4 text-lg text-muted-foreground">Comprehensive support for every aspect of your project.</p></div><div className="mt-16 grid gap-8 md:grid-cols-2 lg:grid-cols-3">{features.map((f, i) => (<Card key={i} className="border-none shadow-lg hover:shadow-xl transition-shadow"><CardContent className="p-6"><div className="flex h-12 w-12 items-center justify-center rounded-lg bg-primary/10"><f.icon className="h-6 w-6 text-primary" /></div><h3 className="mt-4 text-lg font-semibold text-foreground">{f.title}</h3><p className="mt-2 text-muted-foreground">{f.description}</p></CardContent></Card>))}</div></div></section>
    <section className="bg-muted/50 py-16 md:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mx-auto max-w-2xl text-center mb-16"><h2 className="font-serif text-3xl font-bold tracking-tight text-foreground sm:text-4xl">Our Process</h2><p className="mt-4 text-lg text-muted-foreground">A structured approach to ensure your success.</p></div><div className="grid gap-8 md:grid-cols-2 lg:grid-cols-4">{steps.map((s, i) => (<div key={i} className="text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-primary text-2xl font-bold text-primary-foreground">{s.step}</div><h3 className="mt-4 font-semibold text-foreground">{s.title}</h3><p className="mt-2 text-sm text-muted-foreground">{s.description}</p></div>))}</div></div></section>
    <section className="py-16 md:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-12 lg:grid-cols-2 lg:items-center"><div><h2 className="font-serif text-3xl font-bold tracking-tight text-foreground sm:text-4xl">Why Choose Our Literature Review Service?</h2><p className="mt-4 text-lg text-muted-foreground">Here is why scholars trust us with their work.</p><ul className="mt-8 grid gap-3 sm:grid-cols-2">{benefits.map((b, i) => (<li key={i} className="flex items-start gap-2"><CheckCircle className="mt-0.5 h-5 w-5 shrink-0 text-primary" /><span className="text-sm text-muted-foreground">{b}</span></li>))}</ul></div><Card><CardContent className="p-8"><h3 className="text-xl font-semibold text-foreground">Get a Free Consultation</h3><p className="mt-2 text-muted-foreground">Share your requirements and get expert guidance.</p><form className="mt-6 space-y-4"><input type="text" placeholder="Your Name" className="w-full rounded-lg border border-border bg-background px-4 py-3 text-sm focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary" /><input type="email" placeholder="Email Address" className="w-full rounded-lg border border-border bg-background px-4 py-3 text-sm focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary" /><input type="tel" placeholder="Phone Number" className="w-full rounded-lg border border-border bg-background px-4 py-3 text-sm focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary" /><select className="w-full rounded-lg border border-border bg-background px-4 py-3 text-sm text-muted-foreground focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"><option value="">Select Review Type</option><option value="systematic">Systematic Review</option><option value="narrative">Narrative Review</option><option value="scoping">Scoping Review</option><option value="chapter">Thesis Chapter 2</option></select><Button className="w-full" size="lg">Get Free Consultation</Button></form></CardContent></Card></div></div></section>
    <section className="bg-primary py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 text-center"><h2 className="font-serif text-3xl font-bold text-primary-foreground sm:text-4xl">Build a Strong Research Foundation</h2><p className="mx-auto mt-4 max-w-2xl text-lg text-primary-foreground/90">A great literature review is the backbone of any successful thesis or paper.</p><div className="mt-8 flex flex-col items-center justify-center gap-4 sm:flex-row"><Button size="lg" variant="secondary" asChild><Link prefetch={false} href="/contact">Get Started</Link></Button><Button size="lg" variant="outline" className="border-primary-foreground text-black hover:bg-primary-foreground hover:text-primary" asChild><Link prefetch={false} href="/pricing">View Pricing</Link></Button></div></div></section>
  </main><Footer /></div>);
}
