import { Metadata } from "next";
import Link from "next/link";
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { CheckCircle, FileText, BookOpen, Search, Globe, Edit, BarChart3, PenTool, Users, Clock, Shield, Award, Eye,Type,AlignLeft,Languages,FileCheck } from "lucide-react";
export const metadata: Metadata = { title: "Proofreading & Editing | CogniCode", description: "Professional academic proofreading and editing. Grammar, style, clarity, and formatting polished to perfection." };
const features = [
  { icon: Type, title: "Grammar & Spelling", description: "Meticulous correction of all grammatical, spelling, and punctuation errors throughout your document." },
  { icon: AlignLeft, title: "Sentence Structure", description: "Improvement of sentence construction, flow, and readability while maintaining your academic voice." },
  { icon: Languages, title: "Academic Tone", description: "Refinement of language to ensure consistent, formal academic tone for scholarly publication." },
  { icon: Eye, title: "Consistency Checks", description: "Verification of terminology, abbreviations, numbering, heading styles, and formatting consistency." },
  { icon: FileCheck, title: "Citation Verification", description: "Cross-checking of in-text citations with the reference list and ensuring proper formatting." },
  { icon: Edit, title: "Track Changes", description: "All edits delivered with tracked changes so you can see and approve every modification." },
];
const steps = [
  { step: "01", title: "Document Submission", description: "Submit your document along with any style guides or specific editing instructions." },
  { step: "02", title: "First Pass Editing", description: "Thorough review for grammar, clarity, consistency, academic tone, and coherence." },
  { step: "03", title: "Quality Review", description: "A second editor reviews the document to catch any remaining issues." },
  { step: "04", title: "Final Delivery", description: "Receive your polished document with tracked changes and editor summary." },
];
const benefits = ["Native English-speaking editors", "Subject-area editorial expertise", "Two-tier review process", "Track changes included in delivery", "Quick turnaround from 24 hours", "Satisfaction guaranteed", "Editor feedback report included", "Affordable per-page pricing"];
export default function ServicePage() {
  return (<div className="flex min-h-screen flex-col"><Header /><main className="flex-1 mt-17">
    <section className="bg-primary/5 py-16 md:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-12 lg:grid-cols-2 lg:items-center"><div><p className="text-sm font-semibold uppercase tracking-wider text-primary">Proofreading & Editing</p><h1 className="mt-2 font-serif text-4xl font-bold tracking-tight text-foreground sm:text-5xl">Professional Proofreading & Editing Services</h1><p className="mt-6 text-lg leading-8 text-muted-foreground">Polish your academic work to perfection. Our professional editors eliminate errors, enhance clarity, refine tone, and ensure your document meets the highest publication standards.</p><div className="mt-8 flex flex-col gap-4 sm:flex-row"><Button size="lg" asChild><Link href="/contact">Get Started</Link></Button><Button size="lg" variant="outline" asChild><Link href="/samples">View Samples</Link></Button></div></div><div className="space-y-4"><Card className="bg-primary text-primary-foreground"><CardContent className="p-6"><div className="flex items-center gap-4"><Edit className="h-12 w-12" /><div><p className="text-3xl font-bold">12,000+</p><p className="text-sm text-primary-foreground/80">Documents Edited</p></div></div></CardContent></Card><div className="grid grid-cols-2 gap-4"><Card><CardContent className="p-6 text-center"><p className="text-2xl font-bold text-primary">24 Hrs</p><p className="text-sm text-muted-foreground">Express Available</p></CardContent></Card><Card><CardContent className="p-6 text-center"><p className="text-2xl font-bold text-primary">2-Tier</p><p className="text-sm text-muted-foreground">Review Process</p></CardContent></Card></div></div></div></div></section>
    <section className="bg-primary py-8"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="flex flex-wrap items-center justify-center gap-8">{[{ icon: Shield, text: "100% Original" }, { icon: Clock, text: "On-Time Delivery" }, { icon: Users, text: "Expert Writers" }, { icon: Award, text: "Quality Assured" }].map((item, i) => (<div key={i} className="flex items-center gap-2 text-primary-foreground"><item.icon className="h-5 w-5" /><span className="text-sm font-medium">{item.text}</span></div>))}</div></div></section>
    <section className="py-16 md:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mx-auto max-w-2xl text-center"><h2 className="font-serif text-3xl font-bold tracking-tight text-foreground sm:text-4xl">What Our Editing Covers</h2><p className="mt-4 text-lg text-muted-foreground">Comprehensive support for every aspect of your project.</p></div><div className="mt-16 grid gap-8 md:grid-cols-2 lg:grid-cols-3">{features.map((f, i) => (<Card key={i} className="border-none shadow-lg hover:shadow-xl transition-shadow"><CardContent className="p-6"><div className="flex h-12 w-12 items-center justify-center rounded-lg bg-primary/10"><f.icon className="h-6 w-6 text-primary" /></div><h3 className="mt-4 text-lg font-semibold text-foreground">{f.title}</h3><p className="mt-2 text-muted-foreground">{f.description}</p></CardContent></Card>))}</div></div></section>
    <section className="bg-muted/50 py-16 md:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mx-auto max-w-2xl text-center mb-16"><h2 className="font-serif text-3xl font-bold tracking-tight text-foreground sm:text-4xl">Our Process</h2><p className="mt-4 text-lg text-muted-foreground">A structured approach to ensure your success.</p></div><div className="grid gap-8 md:grid-cols-2 lg:grid-cols-4">{steps.map((s, i) => (<div key={i} className="text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-primary text-2xl font-bold text-primary-foreground">{s.step}</div><h3 className="mt-4 font-semibold text-foreground">{s.title}</h3><p className="mt-2 text-sm text-muted-foreground">{s.description}</p></div>))}</div></div></section>
    <section className="py-16 md:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-12 lg:grid-cols-2 lg:items-center"><div><h2 className="font-serif text-3xl font-bold tracking-tight text-foreground sm:text-4xl">Why Choose Our Editing Service?</h2><p className="mt-4 text-lg text-muted-foreground">Here is why scholars trust us with their work.</p><ul className="mt-8 grid gap-3 sm:grid-cols-2">{benefits.map((b, i) => (<li key={i} className="flex items-start gap-2"><CheckCircle className="mt-0.5 h-5 w-5 shrink-0 text-primary" /><span className="text-sm text-muted-foreground">{b}</span></li>))}</ul></div><Card><CardContent className="p-8"><h3 className="text-xl font-semibold text-foreground">Get a Free Consultation</h3><p className="mt-2 text-muted-foreground">Share your requirements and get expert guidance.</p><form className="mt-6 space-y-4"><input type="text" placeholder="Your Name" className="w-full rounded-lg border border-border bg-background px-4 py-3 text-sm focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary" /><input type="email" placeholder="Email Address" className="w-full rounded-lg border border-border bg-background px-4 py-3 text-sm focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary" /><input type="tel" placeholder="Phone Number" className="w-full rounded-lg border border-border bg-background px-4 py-3 text-sm focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary" /><select className="w-full rounded-lg border border-border bg-background px-4 py-3 text-sm text-muted-foreground focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"><option value="">Select Document Type</option><option value="thesis">Thesis / Dissertation</option><option value="journal">Journal Paper</option><option value="conference">Conference Paper</option><option value="report">Research Report</option><option value="other">Other</option></select><Button className="w-full" size="lg">Get Free Consultation</Button></form></CardContent></Card></div></div></section>
    <section className="bg-primary py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 text-center"><h2 className="font-serif text-3xl font-bold text-primary-foreground sm:text-4xl">Ready to Polish Your Academic Work?</h2><p className="mx-auto mt-4 max-w-2xl text-lg text-primary-foreground/90">Submit error-free, professionally edited documents with confidence.</p><div className="mt-8 flex flex-col items-center justify-center gap-4 sm:flex-row"><Button size="lg" variant="secondary" asChild><Link href="/contact">Get Started</Link></Button><Button size="lg" variant="outline" className="border-primary-foreground text-black hover:bg-primary-foreground hover:text-primary" asChild><Link href="/pricing">View Pricing</Link></Button></div></div></section>
  </main><Footer /></div>);
}
